version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web-application/dist/web-application:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web-application
    networks:
      - frontend

  web-application:
    build:
      context: ./web-application
      dockerfile: docker/Dockerfile
    container_name: web-application
    networks:
      - frontend

  kibana:
    image: kibana:8.2.3
    container_name: kibana
    hostname: kibana
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_SSL_VERIFICATIONMODE: "none"
    ports:
      - "5601:5601"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge